def fail():
    print("This task caused a failure")


if __name__ == '__main__':
    fail()
    exit(2)
